#This is a workflow file 

name: Cloudguard Proact code-scan
on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  scan-and-upload:
    name: Scan Code and Upload to S3 Bucket
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
       
      - uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-1
      
      - name: Check Point Cloudguard Proact code scan
        run: |
              #Install Cloudguard serverless plugin
              sudo npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
              #Scan the template file and its artifacts 
              cloudguard proact -m template.yaml -t ${{secrets.CLOUDGUARD_ID}}:${{secrets.CLOUDGUARD_SECRET}}

      - name: Uploading Scan report to S3
        run: |
              pwd
              aws s3 cp ./cloudguard_output/CloudGuardScanReport.html s3://scott-proact-scan-report/`date +"%y"`/`date +"%d"`/`date +"%H%M%S"`report.html

